package com.model;
// Generated 11/05/2018 10:11:48 PM by Hibernate Tools 4.3.1



/**
 * Aplica generated by hbm2java
 */
public class Aplica  implements java.io.Serializable {


     private short aplid;
     private AspirantePonderable aspirantePonderable;
     private Programaofertado programaofertado;
     private ListaAdmitidos listaAdmitidos;

    public Aplica() {
    }

	
    public Aplica(short aplid, AspirantePonderable aspirantePonderable, Programaofertado programaofertado) {
        this.aplid = aplid;
        this.aspirantePonderable = aspirantePonderable;
        this.programaofertado = programaofertado;
    }
    public Aplica(short aplid, AspirantePonderable aspirantePonderable, Programaofertado programaofertado, ListaAdmitidos listaAdmitidos) {
       this.aplid = aplid;
       this.aspirantePonderable = aspirantePonderable;
       this.programaofertado = programaofertado;
       this.listaAdmitidos = listaAdmitidos;
    }
   
    public short getAplid() {
        return this.aplid;
    }
    
    public void setAplid(short aplid) {
        this.aplid = aplid;
    }
    public AspirantePonderable getAspirantePonderable() {
        return this.aspirantePonderable;
    }
    
    public void setAspirantePonderable(AspirantePonderable aspirantePonderable) {
        this.aspirantePonderable = aspirantePonderable;
    }
    public Programaofertado getProgramaofertado() {
        return this.programaofertado;
    }
    
    public void setProgramaofertado(Programaofertado programaofertado) {
        this.programaofertado = programaofertado;
    }
    public ListaAdmitidos getListaAdmitidos() {
        return this.listaAdmitidos;
    }
    
    public void setListaAdmitidos(ListaAdmitidos listaAdmitidos) {
        this.listaAdmitidos = listaAdmitidos;
    }




}


