package com.model;
// Generated 11/05/2018 10:11:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AspirantePonderable generated by hbm2java
 */
public class AspirantePonderable  implements java.io.Serializable {


     private int aspid;
     private String asptipo;
     private String asptipodoc;
     private String aspnombre;
     private Date aspfechanac;
     private short asppondtotal;
     private short asplecturacritica;
     private short aspmatematicas;
     private short aspcsociales;
     private short aspcnaturales;
     private short aspingles;
     private String asptipoinscrito;
     private String aspcorreo;
     private Short asppruebaad;
     private Set<Aplica> aplicas = new HashSet<Aplica>(0);
     private AspiranteNoPonderable aspiranteNoPonderable;

    public AspirantePonderable() {
    }

	
    public AspirantePonderable(int aspid, String asptipo, String asptipodoc, String aspnombre, Date aspfechanac, short asppondtotal, short asplecturacritica, short aspmatematicas, short aspcsociales, short aspcnaturales, short aspingles, String asptipoinscrito, String aspcorreo) {
        this.aspid = aspid;
        this.asptipo = asptipo;
        this.asptipodoc = asptipodoc;
        this.aspnombre = aspnombre;
        this.aspfechanac = aspfechanac;
        this.asppondtotal = asppondtotal;
        this.asplecturacritica = asplecturacritica;
        this.aspmatematicas = aspmatematicas;
        this.aspcsociales = aspcsociales;
        this.aspcnaturales = aspcnaturales;
        this.aspingles = aspingles;
        this.asptipoinscrito = asptipoinscrito;
        this.aspcorreo = aspcorreo;
    }
    public AspirantePonderable(int aspid, String asptipo, String asptipodoc, String aspnombre, Date aspfechanac, short asppondtotal, short asplecturacritica, short aspmatematicas, short aspcsociales, short aspcnaturales, short aspingles, String asptipoinscrito, String aspcorreo, Short asppruebaad, Set<Aplica> aplicas, AspiranteNoPonderable aspiranteNoPonderable) {
       this.aspid = aspid;
       this.asptipo = asptipo;
       this.asptipodoc = asptipodoc;
       this.aspnombre = aspnombre;
       this.aspfechanac = aspfechanac;
       this.asppondtotal = asppondtotal;
       this.asplecturacritica = asplecturacritica;
       this.aspmatematicas = aspmatematicas;
       this.aspcsociales = aspcsociales;
       this.aspcnaturales = aspcnaturales;
       this.aspingles = aspingles;
       this.asptipoinscrito = asptipoinscrito;
       this.aspcorreo = aspcorreo;
       this.asppruebaad = asppruebaad;
       this.aplicas = aplicas;
       this.aspiranteNoPonderable = aspiranteNoPonderable;
    }
   
    public int getAspid() {
        return this.aspid;
    }
    
    public void setAspid(int aspid) {
        this.aspid = aspid;
    }
    public String getAsptipo() {
        return this.asptipo;
    }
    
    public void setAsptipo(String asptipo) {
        this.asptipo = asptipo;
    }
    public String getAsptipodoc() {
        return this.asptipodoc;
    }
    
    public void setAsptipodoc(String asptipodoc) {
        this.asptipodoc = asptipodoc;
    }
    public String getAspnombre() {
        return this.aspnombre;
    }
    
    public void setAspnombre(String aspnombre) {
        this.aspnombre = aspnombre;
    }
    public Date getAspfechanac() {
        return this.aspfechanac;
    }
    
    public void setAspfechanac(Date aspfechanac) {
        this.aspfechanac = aspfechanac;
    }
    public short getAsppondtotal() {
        return this.asppondtotal;
    }
    
    public void setAsppondtotal(short asppondtotal) {
        this.asppondtotal = asppondtotal;
    }
    public short getAsplecturacritica() {
        return this.asplecturacritica;
    }
    
    public void setAsplecturacritica(short asplecturacritica) {
        this.asplecturacritica = asplecturacritica;
    }
    public short getAspmatematicas() {
        return this.aspmatematicas;
    }
    
    public void setAspmatematicas(short aspmatematicas) {
        this.aspmatematicas = aspmatematicas;
    }
    public short getAspcsociales() {
        return this.aspcsociales;
    }
    
    public void setAspcsociales(short aspcsociales) {
        this.aspcsociales = aspcsociales;
    }
    public short getAspcnaturales() {
        return this.aspcnaturales;
    }
    
    public void setAspcnaturales(short aspcnaturales) {
        this.aspcnaturales = aspcnaturales;
    }
    public short getAspingles() {
        return this.aspingles;
    }
    
    public void setAspingles(short aspingles) {
        this.aspingles = aspingles;
    }
    public String getAsptipoinscrito() {
        return this.asptipoinscrito;
    }
    
    public void setAsptipoinscrito(String asptipoinscrito) {
        this.asptipoinscrito = asptipoinscrito;
    }
    public String getAspcorreo() {
        return this.aspcorreo;
    }
    
    public void setAspcorreo(String aspcorreo) {
        this.aspcorreo = aspcorreo;
    }
    public Short getAsppruebaad() {
        return this.asppruebaad;
    }
    
    public void setAsppruebaad(Short asppruebaad) {
        this.asppruebaad = asppruebaad;
    }
    public Set<Aplica> getAplicas() {
        return this.aplicas;
    }
    
    public void setAplicas(Set<Aplica> aplicas) {
        this.aplicas = aplicas;
    }
    public AspiranteNoPonderable getAspiranteNoPonderable() {
        return this.aspiranteNoPonderable;
    }
    
    public void setAspiranteNoPonderable(AspiranteNoPonderable aspiranteNoPonderable) {
        this.aspiranteNoPonderable = aspiranteNoPonderable;
    }




}


