package admisiones.model;
// Generated 07-may-2018 22:32:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Periodo generated by hbm2java
 */
public class Periodo  implements java.io.Serializable {


     private String perid;
     private short perminpop;
     private short perminreg;
     private boolean pervigente;
     private Set<Programaofertado> programaofertados = new HashSet<Programaofertado>(0);

    public Periodo() {
    }

	
    public Periodo(String perid, short perminpop, short perminreg, boolean pervigente) {
        this.perid = perid;
        this.perminpop = perminpop;
        this.perminreg = perminreg;
        this.pervigente = pervigente;
    }
    public Periodo(String perid, short perminpop, short perminreg, boolean pervigente, Set<Programaofertado> programaofertados) {
       this.perid = perid;
       this.perminpop = perminpop;
       this.perminreg = perminreg;
       this.pervigente = pervigente;
       this.programaofertados = programaofertados;
    }
   
    public String getPerid() {
        return this.perid;
    }
    
    public void setPerid(String perid) {
        this.perid = perid;
    }
    public short getPerminpop() {
        return this.perminpop;
    }
    
    public void setPerminpop(short perminpop) {
        this.perminpop = perminpop;
    }
    public short getPerminreg() {
        return this.perminreg;
    }
    
    public void setPerminreg(short perminreg) {
        this.perminreg = perminreg;
    }
    public boolean isPervigente() {
        return this.pervigente;
    }
    
    public void setPervigente(boolean pervigente) {
        this.pervigente = pervigente;
    }
    public Set<Programaofertado> getProgramaofertados() {
        return this.programaofertados;
    }
    
    public void setProgramaofertados(Set<Programaofertado> programaofertados) {
        this.programaofertados = programaofertados;
    }




}


