package com.model;
// Generated 2/06/2018 07:20:11 PM by Hibernate Tools 4.3.1

/**
 * Clase Aplica
 *
 * Aplica generated by hbm2java
 *
 * Contiene la información de un aspirante de un programa ofertado específico
 */
public class Aplica implements java.io.Serializable {

    /*** Atributos ***/ 
    
    /**
     * Id del aspirante 
     */
    private short apliid;
    
    /**
     * Aspirante 
     */
    private Aspirante aspirante;
    
    /**
     * Programa al que se inscribió
     */
    private Programaofertado programaofertado;
    
    /**
     * Prioridad del aspirante
     */
    private boolean apliprioridad;
    
    /**
     * SNP del aspirante
     */
    private String aplisnp;
    
    /**
     * lista de admitidos al programa ofertado
     */
    private ListaAdmitidos listaAdmitidos;

    
    /*** Constructores ***/ 
    
    public Aplica() {
    }

    public Aplica(short apliid, Aspirante aspirante, Programaofertado programaofertado, boolean apliprioridad, String aplisnp) {
        this.apliid = apliid;
        this.aspirante = aspirante;
        this.programaofertado = programaofertado;
        this.apliprioridad = apliprioridad;
        this.aplisnp = aplisnp;
    }

    public Aplica(short apliid, Aspirante aspirante, Programaofertado programaofertado, boolean apliprioridad, String aplisnp, ListaAdmitidos listaAdmitidos) {
        this.apliid = apliid;
        this.aspirante = aspirante;
        this.programaofertado = programaofertado;
        this.apliprioridad = apliprioridad;
        this.aplisnp = aplisnp;
        this.listaAdmitidos = listaAdmitidos;
    }

    
    /*** Métodos getter y setter ***/
    
    public short getApliid() {
        return this.apliid;
    }

    public void setApliid(short apliid) {
        this.apliid = apliid;
    }

    public Aspirante getAspirante() {
        return this.aspirante;
    }

    public void setAspirante(Aspirante aspirante) {
        this.aspirante = aspirante;
    }

    public Programaofertado getProgramaofertado() {
        return this.programaofertado;
    }

    public void setProgramaofertado(Programaofertado programaofertado) {
        this.programaofertado = programaofertado;
    }

    public boolean isApliprioridad() {
        return this.apliprioridad;
    }

    public void setApliprioridad(boolean apliprioridad) {
        this.apliprioridad = apliprioridad;
    }

    public String getAplisnp() {
        return this.aplisnp;
    }

    public void setAplisnp(String aplisnp) {
        this.aplisnp = aplisnp;
    }

    public ListaAdmitidos getListaAdmitidos() {
        return this.listaAdmitidos;
    }

    public void setListaAdmitidos(ListaAdmitidos listaAdmitidos) {
        this.listaAdmitidos = listaAdmitidos;
    }

}
