package com.model;
// Generated 2/06/2018 07:20:11 PM by Hibernate Tools 4.3.1



/**
 * Aplica generated by hbm2java
 * Contiene la información de un aspirante de un programa ofertado específico
 */
public class Aplica  implements java.io.Serializable {


     private short apliid;
     private Aspirante aspirante;
     private Programaofertado programaofertado;
     private boolean apliprioridad;
     private String aplisnp;
     private ListaAdmitidos listaAdmitidos;

    public Aplica() {
    }

	
    public Aplica(short apliid, Aspirante aspirante, Programaofertado programaofertado, boolean apliprioridad, String aplisnp) {
        this.apliid = apliid;
        this.aspirante = aspirante;
        this.programaofertado = programaofertado;
        this.apliprioridad = apliprioridad;
        this.aplisnp = aplisnp;
    }
    public Aplica(short apliid, Aspirante aspirante, Programaofertado programaofertado, boolean apliprioridad, String aplisnp, ListaAdmitidos listaAdmitidos) {
       this.apliid = apliid;
       this.aspirante = aspirante;
       this.programaofertado = programaofertado;
       this.apliprioridad = apliprioridad;
       this.aplisnp = aplisnp;
       this.listaAdmitidos = listaAdmitidos;
    }
   
    public short getApliid() {
        return this.apliid;
    }
    
    public void setApliid(short apliid) {
        this.apliid = apliid;
    }
    public Aspirante getAspirante() {
        return this.aspirante;
    }
    
    public void setAspirante(Aspirante aspirante) {
        this.aspirante = aspirante;
    }
    public Programaofertado getProgramaofertado() {
        return this.programaofertado;
    }
    
    public void setProgramaofertado(Programaofertado programaofertado) {
        this.programaofertado = programaofertado;
    }
    public boolean isApliprioridad() {
        return this.apliprioridad;
    }
    
    public void setApliprioridad(boolean apliprioridad) {
        this.apliprioridad = apliprioridad;
    }
    public String getAplisnp() {
        return this.aplisnp;
    }
    
    public void setAplisnp(String aplisnp) {
        this.aplisnp = aplisnp;
    }
    public ListaAdmitidos getListaAdmitidos() {
        return this.listaAdmitidos;
    }
    
    public void setListaAdmitidos(ListaAdmitidos listaAdmitidos) {
        this.listaAdmitidos = listaAdmitidos;
    }




}


