package com.model;
// Generated 2/06/2018 07:20:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Aspirante generated by hbm2java
 * Contiene la información de un Aspirante (que se puede ponderar)
 */
public class Aspirante  implements java.io.Serializable {


     private int aspid;
     private String asptipodoc;
     private String aspnombre;
     private Date aspfechanac;
     private String asptipoinscrito;
     private String aspcorreo;
     private Set<Aplica> aplicas = new HashSet<Aplica>(0);
     private AspirantePonderable aspirantePonderable;

    public Aspirante() {
    }

	
    public Aspirante(int aspid, String asptipodoc, String aspnombre, Date aspfechanac, String asptipoinscrito, String aspcorreo) {
        this.aspid = aspid;
        this.asptipodoc = asptipodoc;
        this.aspnombre = aspnombre;
        this.aspfechanac = aspfechanac;
        this.asptipoinscrito = asptipoinscrito;
        this.aspcorreo = aspcorreo;
    }
    public Aspirante(int aspid, String asptipodoc, String aspnombre, Date aspfechanac, String asptipoinscrito, String aspcorreo, Set<Aplica> aplicas, AspirantePonderable aspirantePonderable) {
       this.aspid = aspid;
       this.asptipodoc = asptipodoc;
       this.aspnombre = aspnombre;
       this.aspfechanac = aspfechanac;
       this.asptipoinscrito = asptipoinscrito;
       this.aspcorreo = aspcorreo;
       this.aplicas = aplicas;
       this.aspirantePonderable = aspirantePonderable;
    }
   
    public int getAspid() {
        return this.aspid;
    }
    
    public void setAspid(int aspid) {
        this.aspid = aspid;
    }
    public String getAsptipodoc() {
        return this.asptipodoc;
    }
    
    public void setAsptipodoc(String asptipodoc) {
        this.asptipodoc = asptipodoc;
    }
    public String getAspnombre() {
        return this.aspnombre;
    }
    
    public void setAspnombre(String aspnombre) {
        this.aspnombre = aspnombre;
    }
    public Date getAspfechanac() {
        return this.aspfechanac;
    }
    
    public void setAspfechanac(Date aspfechanac) {
        this.aspfechanac = aspfechanac;
    }
    public String getAsptipoinscrito() {
        return this.asptipoinscrito;
    }
    
    public void setAsptipoinscrito(String asptipoinscrito) {
        this.asptipoinscrito = asptipoinscrito;
    }
    public String getAspcorreo() {
        return this.aspcorreo;
    }
    
    public void setAspcorreo(String aspcorreo) {
        this.aspcorreo = aspcorreo;
    }
    public Set<Aplica> getAplicas() {
        return this.aplicas;
    }
    
    public void setAplicas(Set<Aplica> aplicas) {
        this.aplicas = aplicas;
    }
    public AspirantePonderable getAspirantePonderable() {
        return this.aspirantePonderable;
    }
    
    public void setAspirantePonderable(AspirantePonderable aspirantePonderable) {
        this.aspirantePonderable = aspirantePonderable;
    }




}


