package com.model;
// Generated 2/06/2018 07:20:11 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Clase Facultad 
 * 
 * Facultad generated by hbm2java 
 * 
 * Contiene la información de una facultad
 */
public class Facultad implements java.io.Serializable {

    /*** Atributos ***/
    
    /**
     * ID de la facultad
     */
    private short facid;
    
    /**
     * Nombre de la facultad 
     */
    private String facnombre;
    
    /**
     * Programas que pertenecen a la facultad
     */
    private Set<Programa> programas = new HashSet<Programa>(0);

    
    /*** Constructores ***/
    
    public Facultad() {
    }

    public Facultad(short facid, String facnombre) {
        this.facid = facid;
        this.facnombre = facnombre;
    }

    public Facultad(short facid, String facnombre, Set<Programa> programas) {
        this.facid = facid;
        this.facnombre = facnombre;
        this.programas = programas;
    }

    
    /*** Métodos getter y setter ***/ 
    
    public short getFacid() {
        return this.facid;
    }

    public void setFacid(short facid) {
        this.facid = facid;
    }

    public String getFacnombre() {
        return this.facnombre;
    }

    public void setFacnombre(String facnombre) {
        this.facnombre = facnombre;
    }

    public Set<Programa> getProgramas() {
        return this.programas;
    }

    public void setProgramas(Set<Programa> programas) {
        this.programas = programas;
    }

}
