package com.model;
// Generated 2/06/2018 07:20:11 PM by Hibernate Tools 4.3.1



/**
 * ListaAdmitidos generated by hbm2java
 * Contiene la lista de aspirantes ponderables que han sido admitidos a un programa
 */
public class ListaAdmitidos  implements java.io.Serializable {


     private short apliid;
     private Aplica aplica;
     private String listestado;
     private String listtipoadmitido;

    public ListaAdmitidos() {
    }

    public ListaAdmitidos(Aplica aplica, String listestado, String listtipoadmitido) {
       this.aplica = aplica;
       this.listestado = listestado;
       this.listtipoadmitido = listtipoadmitido;
    }
   
    public short getApliid() {
        return this.apliid;
    }
    
    public void setApliid(short apliid) {
        this.apliid = apliid;
    }
    public Aplica getAplica() {
        return this.aplica;
    }
    
    public void setAplica(Aplica aplica) {
        this.aplica = aplica;
    }
    public String getListestado() {
        return this.listestado;
    }
    
    public void setListestado(String listestado) {
        this.listestado = listestado;
    }
    public String getListtipoadmitido() {
        return this.listtipoadmitido;
    }
    
    public void setListtipoadmitido(String listtipoadmitido) {
        this.listtipoadmitido = listtipoadmitido;
    }




}


