package com.model;
// Generated 2/06/2018 07:20:11 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Clase Periodo 
 * 
 * Periodo generated by hbm2java 
 * 
 * Contiene la información de un periodo académico
 */
public class Periodo implements java.io.Serializable {

    /*** Atributos ***/ 
    
    /**
     * ID del periodo académico
     */
    private String perid;
    
    /**
     * Puntaje mínimo para programas Popayán 
     */
    private short perminpop;
    
    /**
     * Puntaje mínimo para programas de Regionalización 
     */
    private short perminreg;
    
    /**
     * Periodo actual vigente 
     */
    private boolean pervigente;
    
    /**
     * Programas ofertados en periodos académicos 
     */
    private Set<Programaofertado> programaofertados = new HashSet<Programaofertado>(0);

    
    /*** Constructores ***/ 
    
    public Periodo() {
    }

    public Periodo(String perid, short perminpop, short perminreg, boolean pervigente) {
        this.perid = perid;
        this.perminpop = perminpop;
        this.perminreg = perminreg;
        this.pervigente = pervigente;
    }

    public Periodo(String perid, short perminpop, short perminreg, boolean pervigente, Set<Programaofertado> programaofertados) {
        this.perid = perid;
        this.perminpop = perminpop;
        this.perminreg = perminreg;
        this.pervigente = pervigente;
        this.programaofertados = programaofertados;
    }
    
    
    /*** Métodos getter y setter ***/

    public String getPerid() {
        return this.perid;
    }

    public void setPerid(String perid) {
        this.perid = perid;
    }

    public short getPerminpop() {
        return this.perminpop;
    }

    public void setPerminpop(short perminpop) {
        this.perminpop = perminpop;
    }

    public short getPerminreg() {
        return this.perminreg;
    }

    public void setPerminreg(short perminreg) {
        this.perminreg = perminreg;
    }

    public boolean isPervigente() {
        return this.pervigente;
    }

    public void setPervigente(boolean pervigente) {
        this.pervigente = pervigente;
    }

    public Set<Programaofertado> getProgramaofertados() {
        return this.programaofertados;
    }

    public void setProgramaofertados(Set<Programaofertado> programaofertados) {
        this.programaofertados = programaofertados;
    }

}
