package com.model;
// Generated 2/06/2018 07:20:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clase Programaofertado
 * 
 * Programaofertado generated by hbm2java
 * 
 * Contiene la información de un programa que se oferta durante un periodo académico
 */
public class Programaofertado implements java.io.Serializable {

    /*** Atributos ***/
    
    /**
     * Id del programa ofertado 
     */
    private short pofid;
    
    /**
     * Periodo académico en el cual se oferta 
     */
    private Periodo periodo;
    
    /**
     * Información del programa ofertado
     */
    private Programa programa;
    
    /**
     * Cupos regulares 
     */
    private byte pofcuposreg;
    
    /**
     * Cupos Zona Marginal
     */
    private byte pofcuposzonamarginal;
    
    /**
     * Cupos zona de difícil acceso
     */
    private byte pofcuposdificilacceso;
    
    /**
     * Cupos normalistas 
     */
    private byte pofcuposnormalista;
    
    /**
     * Cupos indígenas
     */
    private byte pofcuposindigena;
    
    /**
     * Cupos afrodescendientes
     */
    private byte pofcuposafrodescendiente;
    
    /**
     * Cupos costa pacífica
     */
    private byte pofcuposcostapacifica;
    
    /**
     * Ponderados lectura crítica
     */
    private byte pofpondlecturacritica;
    
    /**
     * Ponderados matemáticas 
     */
    private byte pofpondmatematicas;
    
    /**
     * Ponderados ciencias sociales
     */
    private byte pofpondcsociales;
    
    /**
     * Ponderados ciencias naturales 
     */
    private byte pofpondcnaturales;
    
    /**
     * Ponderados inglés 
     */
    private byte pofpondingles;
    
    /**
     * Porcentaje prueba adicional
     */
    private Byte pofpondpruebaad;
    
    /**
     * Total lista de espera 
     */
    private byte poflistaespera;
    
    /**
     * Cupos Totales 
     */
    private byte poftotalcupos;
    
    /**
     * Referencia de un aspirante a un programa ofertado
     */
    private Set<Aplica> aplicas = new HashSet<Aplica>(0);

    
    /*** Constructores ***/
    
    public Programaofertado() {
    }

    public Programaofertado(short pofid, Periodo periodo, Programa programa, byte pofcuposreg, byte pofcuposzonamarginal, byte pofcuposdificilacceso, byte pofcuposnormalista, byte pofcuposindigena, byte pofcuposafrodescendiente, byte pofcuposcostapacifica, byte pofpondlecturacritica, byte pofpondmatematicas, byte pofpondcsociales, byte pofpondcnaturales, byte pofpondingles, byte poflistaespera, byte poftotalcupos) {
        this.pofid = pofid;
        this.periodo = periodo;
        this.programa = programa;
        this.pofcuposreg = pofcuposreg;
        this.pofcuposzonamarginal = pofcuposzonamarginal;
        this.pofcuposdificilacceso = pofcuposdificilacceso;
        this.pofcuposnormalista = pofcuposnormalista;
        this.pofcuposindigena = pofcuposindigena;
        this.pofcuposafrodescendiente = pofcuposafrodescendiente;
        this.pofcuposcostapacifica = pofcuposcostapacifica;
        this.pofpondlecturacritica = pofpondlecturacritica;
        this.pofpondmatematicas = pofpondmatematicas;
        this.pofpondcsociales = pofpondcsociales;
        this.pofpondcnaturales = pofpondcnaturales;
        this.pofpondingles = pofpondingles;
        this.poflistaespera = poflistaespera;
        this.poftotalcupos = poftotalcupos;
    }

    public Programaofertado(short pofid, Periodo periodo, Programa programa, byte pofcuposreg, byte pofcuposzonamarginal, byte pofcuposdificilacceso, byte pofcuposnormalista, byte pofcuposindigena, byte pofcuposafrodescendiente, byte pofcuposcostapacifica, byte pofpondlecturacritica, byte pofpondmatematicas, byte pofpondcsociales, byte pofpondcnaturales, byte pofpondingles, Byte pofpondpruebaad, byte poflistaespera, byte poftotalcupos, Set<Aplica> aplicas) {
        this.pofid = pofid;
        this.periodo = periodo;
        this.programa = programa;
        this.pofcuposreg = pofcuposreg;
        this.pofcuposzonamarginal = pofcuposzonamarginal;
        this.pofcuposdificilacceso = pofcuposdificilacceso;
        this.pofcuposnormalista = pofcuposnormalista;
        this.pofcuposindigena = pofcuposindigena;
        this.pofcuposafrodescendiente = pofcuposafrodescendiente;
        this.pofcuposcostapacifica = pofcuposcostapacifica;
        this.pofpondlecturacritica = pofpondlecturacritica;
        this.pofpondmatematicas = pofpondmatematicas;
        this.pofpondcsociales = pofpondcsociales;
        this.pofpondcnaturales = pofpondcnaturales;
        this.pofpondingles = pofpondingles;
        this.pofpondpruebaad = pofpondpruebaad;
        this.poflistaespera = poflistaespera;
        this.poftotalcupos = poftotalcupos;
        this.aplicas = aplicas;
    }

    
    /*** Métodos getter y setter ***/
    
    public short getPofid() {
        return this.pofid;
    }

    public void setPofid(short pofid) {
        this.pofid = pofid;
    }

    public Periodo getPeriodo() {
        return this.periodo;
    }

    public void setPeriodo(Periodo periodo) {
        this.periodo = periodo;
    }

    public Programa getPrograma() {
        return this.programa;
    }

    public void setPrograma(Programa programa) {
        this.programa = programa;
    }

    public byte getPofcuposreg() {
        return this.pofcuposreg;
    }

    public void setPofcuposreg(byte pofcuposreg) {
        this.pofcuposreg = pofcuposreg;
    }

    public byte getPofcuposzonamarginal() {
        return this.pofcuposzonamarginal;
    }

    public void setPofcuposzonamarginal(byte pofcuposzonamarginal) {
        this.pofcuposzonamarginal = pofcuposzonamarginal;
    }

    public byte getPofcuposdificilacceso() {
        return this.pofcuposdificilacceso;
    }

    public void setPofcuposdificilacceso(byte pofcuposdificilacceso) {
        this.pofcuposdificilacceso = pofcuposdificilacceso;
    }

    public byte getPofcuposnormalista() {
        return this.pofcuposnormalista;
    }

    public void setPofcuposnormalista(byte pofcuposnormalista) {
        this.pofcuposnormalista = pofcuposnormalista;
    }

    public byte getPofcuposindigena() {
        return this.pofcuposindigena;
    }

    public void setPofcuposindigena(byte pofcuposindigena) {
        this.pofcuposindigena = pofcuposindigena;
    }

    public byte getPofcuposafrodescendiente() {
        return this.pofcuposafrodescendiente;
    }

    public void setPofcuposafrodescendiente(byte pofcuposafrodescendiente) {
        this.pofcuposafrodescendiente = pofcuposafrodescendiente;
    }

    public byte getPofcuposcostapacifica() {
        return this.pofcuposcostapacifica;
    }

    public void setPofcuposcostapacifica(byte pofcuposcostapacifica) {
        this.pofcuposcostapacifica = pofcuposcostapacifica;
    }

    public byte getPofpondlecturacritica() {
        return this.pofpondlecturacritica;
    }

    public void setPofpondlecturacritica(byte pofpondlecturacritica) {
        this.pofpondlecturacritica = pofpondlecturacritica;
    }

    public byte getPofpondmatematicas() {
        return this.pofpondmatematicas;
    }

    public void setPofpondmatematicas(byte pofpondmatematicas) {
        this.pofpondmatematicas = pofpondmatematicas;
    }

    public byte getPofpondcsociales() {
        return this.pofpondcsociales;
    }

    public void setPofpondcsociales(byte pofpondcsociales) {
        this.pofpondcsociales = pofpondcsociales;
    }

    public byte getPofpondcnaturales() {
        return this.pofpondcnaturales;
    }

    public void setPofpondcnaturales(byte pofpondcnaturales) {
        this.pofpondcnaturales = pofpondcnaturales;
    }

    public byte getPofpondingles() {
        return this.pofpondingles;
    }

    public void setPofpondingles(byte pofpondingles) {
        this.pofpondingles = pofpondingles;
    }

    public Byte getPofpondpruebaad() {
        return this.pofpondpruebaad;
    }

    public void setPofpondpruebaad(Byte pofpondpruebaad) {
        this.pofpondpruebaad = pofpondpruebaad;
    }

    public byte getPoflistaespera() {
        return this.poflistaespera;
    }

    public void setPoflistaespera(byte poflistaespera) {
        this.poflistaespera = poflistaespera;
    }

    public byte getPoftotalcupos() {
        return this.poftotalcupos;
    }

    public void setPoftotalcupos(byte poftotalcupos) {
        this.poftotalcupos = poftotalcupos;
    }

    public Set<Aplica> getAplicas() {
        return this.aplicas;
    }

    public void setAplicas(Set<Aplica> aplicas) {
        this.aplicas = aplicas;
    }

}
